#!/usr/bin/env python3
"""Embed every shippable file under 010_interface/ into a single C++ source
file. The generated module exposes a path-keyed lookup that the HTTP
server uses to serve assets directly from binary memory.

Usage:
    embed_assets.py <src_dir> <out_cpp> <out_hpp>

The src_dir is walked recursively. Files with extensions in EXTS are
embedded; everything else is skipped (notably httplib.h and *.py).
"""
import os
import sys

EXTS = {
    '.html': 'text/html; charset=utf-8',
    '.htm':  'text/html; charset=utf-8',
    '.css':  'text/css; charset=utf-8',
    '.js':   'application/javascript; charset=utf-8',
    '.mjs':  'application/javascript; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.svg':  'image/svg+xml',
    '.png':  'image/png',
    '.jpg':  'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif':  'image/gif',
    '.ico':  'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf':  'font/ttf',
    '.map':  'application/json; charset=utf-8',
    '.txt':  'text/plain; charset=utf-8',
    '.wasm': 'application/wasm',
}

def sanitize(name: str) -> str:
    return ''.join(c if c.isalnum() else '_' for c in name)

def main(src_dir: str, out_cpp: str, out_hpp: str) -> None:
    files = []
    for root, _, names in os.walk(src_dir):
        for n in sorted(names):
            ext = os.path.splitext(n)[1].lower()
            if ext not in EXTS:
                continue
            abspath = os.path.join(root, n)
            relpath = os.path.relpath(abspath, src_dir).replace(os.sep, '/')
            url = '/' + relpath
            files.append((url, abspath, EXTS[ext]))
    files.sort()

    out_dir = os.path.dirname(out_cpp)
    os.makedirs(out_dir, exist_ok=True)

    with open(out_hpp, 'w') as h:
        h.write("""// Auto-generated by 010_interface/embed_assets.py. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <string_view>

namespace interface_assets {

struct Asset {
    const char *         path;
    const unsigned char* data;
    std::size_t          size;
    const char *         mime;
};

// Returns nullptr if no asset matches `url`. Match is exact, and "/" is
// rewritten to "/index.html".
const Asset * find(std::string_view url);

// First / last for range iteration if needed.
const Asset * begin();
const Asset * end();

}
""")

    with open(out_cpp, 'w') as c:
        c.write('// Auto-generated by 010_interface/embed_assets.py. DO NOT EDIT.\n')
        c.write('#include "assets_gen.hpp"\n\n')
        c.write('#include <cstring>\n\n')
        c.write('namespace interface_assets {\nnamespace {\n\n')

        # Per-file byte arrays.
        for url, path, _mime in files:
            sym = sanitize(url)
            with open(path, 'rb') as f:
                data = f.read()
            c.write(f'// {url}  ({len(data)} bytes)\n')
            c.write(f'const unsigned char data{sym}[] = {{\n')
            for i in range(0, len(data), 16):
                row = ', '.join(f'0x{b:02x}' for b in data[i:i+16])
                c.write(f'    {row},\n')
            c.write('};\n')
            c.write(f'constexpr std::size_t size{sym} = sizeof(data{sym});\n\n')

        # Lookup table.
        c.write('const Asset kAssets[] = {\n')
        for url, _path, mime in files:
            sym = sanitize(url)
            c.write(f'    {{ "{url}", data{sym}, size{sym}, "{mime}" }},\n')
        c.write('};\n')
        c.write(f'constexpr std::size_t kAssetCount = sizeof(kAssets) / sizeof(kAssets[0]);\n\n')

        c.write('}\n\n')

        c.write('const Asset * find(std::string_view url) {\n')
        c.write('    if (url == "/") url = "/index.html";\n')
        c.write('    for (std::size_t i = 0; i < kAssetCount; ++i) {\n')
        c.write('        if (url == kAssets[i].path) return &kAssets[i];\n')
        c.write('    }\n')
        c.write('    return nullptr;\n')
        c.write('}\n\n')

        c.write('const Asset * begin() { return kAssets; }\n')
        c.write('const Asset * end()   { return kAssets + kAssetCount; }\n')
        c.write('\n}\n')


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print('usage: embed_assets.py <src_dir> <out_cpp> <out_hpp>', file=sys.stderr)
        sys.exit(2)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
